FROM python:3.10

# 设置工作目录
WORKDIR /app

# 拷贝依赖文件并安装
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 8000

# 启动 FastAPI 应用
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"]
